### ISSUE TITLE
Add support for IoTeX RPC

### ISSUE THREAD

**Issue by vikmeup** [trustwallet/web-core#80]
Example Cosmos RPC: https://github.com/trustwallet/web-core/tree/master/packages/rpc/src/cosmos

Endpoint: for testing: `https://pharos.iotex.io/`

Replicate Swift implementation in TypeScript, as implemented in Cosmos RPC

Swift implementation:
```swift
var path: String {
        switch self {
        case .account(let address):
            return "/v1/accounts/\(address)"
        case .transaction(let hash):
            return "/v1/actions/hash/\(hash)"
        case .broadcast(let data):
            return "/v1/actionbytes/\(data.hexString)"
        }
    }

    var method: Moya.Method {
        switch self {
        case .account, .transaction:
            return .get
        case .broadcast:
            return .post
        }
    }

    var sampleData: Data {
        return Data()
    }

    var task: Task {
        switch self {
        case .account, .transaction, .broadcast:
            return .requestPlain
        }
    }

    var headers: [String: String]? {
        return [
            "content-type": "application/json",
        ]
    }
```

Models:

```swift
struct IoTeXAccountMeta: Codable {
    let balance: BigIntCodable
    let pendingNonce: String
}

struct IoTeXAccount: Codable {
    let accountMeta: IoTeXAccountMeta
}

struct IoTexAction: Codable {
    let blkHeight: BigIntCodable
}

struct IoTexTransaction: Codable {
    let actionInfo: [IoTexAction]
}

struct IoTexSentTransaction: Codable {
    let actionHash: String
}
```

**Comment by akinmail** [comment]
Is data.hexString the hex value of IoTexSentTransaction? I could not find an api like that in Iotex's api.

**Comment by vikmeup** [comment]
> Is data.hexString the hex value of IoTexSentTransaction? I could not find an api like that in Iotex's api.

Yes, it would he hex value of the raw transaction, something like `0x1234`.

**Comment by aakindeleseso** [comment]
Hi @vikmeup, this is a sample transaction
{
  "total": "1",
  "actionInfo": [
    {
      "action": {
        "core": {
          "version": 1,
          "gasPrice": "0",
          "grantReward": {
            "height": "1159764"
          }
        },
        "senderPubKey": "BJ+SfKEIAt6R7WoOGJTQWxF7uyQ2lcxr5tJyFRB6jPp5Gbt9IEHhXIggFGw3IrQhFguEfaxgq5UTPu7l+VGl3W4=",
        "signature": "vOc/e0SPvqKk0VN+Sn4XynTo3zJ70c4Q900ty/It5i4l9fyhRRq4EE7FDr9KWhcQvnZAmk63p9tZ1FD1OIDwbAE="
      },
      "actHash": "42a00398213168b143714a26ba135f81c262bf9546c1d9f3e1c47385ec4a7379",
      "blkHash": "0da4ffc13f89f345674ffa91392de91922245ce808953a52c1ccda9ce60f3748",
      "blkHeight": "1159764",
      "sender": "io1wl83n3up9w8nedf30lnyxzple0gu5pme0dyrds",
      "gasFee": "0",
      "timestamp": "2019-09-04T06:42:40Z"
    }
  ]
}

i have tried 
GET https://pharos.iotex.io/v1/actionbytes/0x{hex of signature param in the object above} --> 404 

GET https://pharos.iotex.io/v1/actionbytes/0x{hex of the whole transaction object} ---> 404

GET https://pharos.iotex.io/v1/actionbytes/0x{hex of just the actHash} ---> 404

what is the correct thing I am supposed to hex and pass?

**Comment by aakindeleseso** [comment]
Or if you could point me to the documentation for this actionbytes endpoint, it would be better. Because i couldn't find the documentation here https://docs.iotex.io/docs/libraries-and-tools.html#rpc-methods

**Comment by akinmail** [comment]
Hi @vikmeup, this is a sample transaction  iotex

{ "total": "1", "actionInfo": [ { "action": { "core": { "version": 1, "gasPrice": "0", "grantReward": { "height": "1159764" } }, "senderPubKey": "BJ+SfKEIAt6R7WoOGJTQWxF7uyQ2lcxr5tJyFRB6jPp5Gbt9IEHhXIggFGw3IrQhFguEfaxgq5UTPu7l+VGl3W4=", "signature": "vOc/e0SPvqKk0VN+Sn4XynTo3zJ70c4Q900ty/It5i4l9fyhRRq4EE7FDr9KWhcQvnZAmk63p9tZ1FD1OIDwbAE=" }, "actHash": "42a00398213168b143714a26ba135f81c262bf9546c1d9f3e1c47385ec4a7379", "blkHash": "0da4ffc13f89f345674ffa91392de91922245ce808953a52c1ccda9ce60f3748", "blkHeight": "1159764", "sender": "io1wl83n3up9w8nedf30lnyxzple0gu5pme0dyrds", "gasFee": "0", "timestamp": "2019-09-04T06:42:40Z" } ] }

For the broadcast endpoint, i have tried all combinations of the apis below
GET https://pharos.iotex.io/v1/actionbytes/0x{hex of signature param in the object above} --> 404
GET https://pharos.iotex.io/v1/actionbytes/0x{hex of the whole transaction object} ---> 404
GET https://pharos.iotex.io/v1/actionbytes/0x{hex of just the actHash} ---> 404
POST https://pharos.iotex.io/v1/actionbytes/0x{hex of signature param in the object above} --> 405
POST https://pharos.iotex.io/v1/actionbytes/0x{hex of the whole transaction object} ---> 405
POST https://pharos.iotex.io/v1/actionbytes/0x{hex of just the actHash} ---> 405
what is the correct thing I am supposed to hex and pass?
Or if you could point me to the documentation for this actionbytes endpoint, it would be better. Because i couldn't find the documentation here https://docs.iotex.io/docs/libraries-and-tools.html#rpc-methods
